version: '3.8'
services:
  user-service:
    build: ./services/user-service
    ports:
      - '3001:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/users
  mongo:
    image: mongo
    ports:
      - '27017:27017'